# Generated by Django 3.1.2 on 2020-11-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_text', models.CharField(max_length=200)),
                ('password_text', models.CharField(max_length=200)),
                ('name_text', models.CharField(max_length=200)),
                ('account_number', models.IntegerField(verbose_name=-1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_text', models.CharField(max_length=200)),
                ('password_text', models.CharField(max_length=200)),
                ('name_text', models.CharField(max_length=200)),
                ('account_number', models.IntegerField(verbose_name=-1)),
                ('address_text', models.CharField(max_length=200)),
                ('bill_address_text', models.CharField(max_length=200)),
                ('email_text', models.CharField(max_length=200)),
                ('CC_info', models.CharField(max_length=200)),
                ('save_CC', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
