# Generated by Django 3.1.2 on 2020-11-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custPort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='save_CC',
            field=models.BooleanField(help_text='Save Credit Card info?', verbose_name=False),
        ),
    ]
