# Generated by Django 3.1.2 on 2020-11-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custPort', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_number_int',
            new_name='account_number',
        ),
    ]
