# Generated by Django 3.1.2 on 2020-11-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custPort', '0002_auto_20201116_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='account_number',
            field=models.IntegerField(help_text='Account Number', verbose_name=-1),
        ),
    ]
